version: 2

gradle_cache_key: &gradle_cache_key gradle-{{ checksum "build.gradle" }}-{{ checksum "remote-config/build.gradle" }}
maven_cache_key: &maven_cache_key maven-{{ checksum "remote-config/src/test/kotlin/com/rakuten/tech/mobile/remoteconfig/RobolectricBaseSpec.kt" }}

jobs:
  build:
    docker:
    - image: circleci/android:api-28
    working_directory: ~/code
    environment:
      JVM_OPTS: "-Xmx3200m"
    steps:
    - checkout
    - run: git submodule update --init --recursive
    - restore_cache:
        key: *gradle_cache_key
    - run:
        name: Download Dependencies
        command: ./gradlew androidDependencies
    - save_cache:
        paths:
        - ~/.gradle
        key: *gradle_cache_key
    - restore_cache:
        ## Robolectric uses maven to download sources, so we must use a different cache for maven
        key: *maven_cache_key
    - run:
        name: Run Tests
        command: ./gradlew check
    - save_cache:
        paths:
        - ~/.m2
        key: *maven_cache_key
    - run:
        name: Assemble AAR
        command: ./gradlew assemble
    - store_artifacts:
        path: remote-config/build/reports
        destination: reports/
    - store_test_results:
        path: remote-config/build/test-results
    - store_artifacts:
        path: remote-config/build/libs
        destination: jar/
    - store_artifacts:
        path: remote-config/build/bin/ios
        destination: ios/
